"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+35fc5q^zto)w2+ukhl$d!+5@kay-hsr9qc1a1k54m%68e)lb$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'search_app',
    'music_app',
    'podcast_app',
    'radio_app',
    
    'rest_framework',
    'mptt',
    'django_elasticsearch_dsl',
    'django_elasticsearch_dsl_drf',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {},
    'music_db': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'music-database',
        #'user=postgres dbname=controller-service-database'
        'USER': 'music_database_admin',
        'PASSWORD': 'HbmYAAKOgqUyShCGwXms79HpSvPLd8',
        'HOST': '34.79.175.51',
        'PORT': '5432',
        #'sslmode': 'disable', 
    
    'OPTIONS': {
        'sslmode': 'verify-ca', #leave this line intact
        'sslrootcert': '/home/sabian/Desktop/search_final/certeficates/server-ca.pem',
        'sslcert': "/home/sabian/Desktop/search_final/certeficates/client-cert.pem",
        'sslkey': "/home/sabian/Desktop/search_final/certeficates/client-key.pem",
        }
    },
    'podcast_db': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'podcast-database',
        #'user=postgres dbname=controller-service-database'
        'USER': 'podcast_database_admin',
        'PASSWORD': '9gxX5r3BdnqlTcTMkhe7ZnHkereEWH',
        'HOST': '34.79.175.51',
        'PORT': '5432',
        #'sslmode': 'disable', 
    
    'OPTIONS': {
        'sslmode': 'verify-ca', #leave this line intact
        'sslrootcert': '/home/sabian/Desktop/search_final/certeficates/server-ca.pem',
        'sslcert': "/home/sabian/Desktop/search_final/certeficates/client-cert.pem",
        'sslkey': "/home/sabian/Desktop/search_final/certeficates/client-key.pem",
        }
    },
    'radio_db': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'radio-database',
        #'user=postgres dbname=controller-service-database'
        'USER': 'radio_database_admin',
        'PASSWORD': 'XuSynuwKH7VDjG7TdyfIxkbSzvXAHo',
        'HOST': '34.79.175.51',
        'PORT': '5432',
        #'sslmode': 'disable', 
    
    'OPTIONS': {
        'sslmode': 'verify-ca', #leave this line intact
        'sslrootcert': '/home/sabian/Desktop/search_final/certeficates/server-ca.pem',
        'sslcert': "/home/sabian/Desktop/search_final/certeficates/client-cert.pem",
        'sslkey': "/home/sabian/Desktop/search_final/certeficates/client-key.pem",
        }
}
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASE_ROUTERS = ['db_routers.routers.SearchRouter', 'db_routers.routers.MusicRouter', 'db_routers.routers.PodcastRouter','db_routers.routers.RadioRouter']

ELASTICSEARCH_DSL = {"default": {"hosts": "localhost:9200"}}

# ELASTICSEARCH_INDEX_NAMES = {
#     'search_indexes.documents.book': 'book',
#     'search_indexes.documents.publisher': 'publisher',
# }

